-- Additive schema; pre-change copies are in pointage_backup_20261001.
create schema if not exists pointage_internal;
revoke all on schema pointage_internal from public,anon;
grant usage on schema pointage_internal to authenticated;
create table public.pointage_code_catalogue (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now());
create table public.pointage_code_versions (
 id bigint generated by default as identity primary key,
 catalogue_id uuid not null references public.pointage_code_catalogue(id),
 unit_id uuid not null references public.units(id),
 effective_month text not null check (effective_month ~ '^[1-9][0-9]{3}-(0[1-9]|1[0-2])$'),
 code text not null check(length(btrim(code)) between 1 and 30),
 label text not null check(length(btrim(label)) between 1 and 300),
 document text not null default '' check(length(document)<=2000),
 active boolean not null default true,
 unique(catalogue_id,unit_id,effective_month)
);
alter table public.pointage_code_catalogue enable row level security;
alter table public.pointage_code_versions enable row level security;
revoke all on public.pointage_code_catalogue,public.pointage_code_versions from anon,authenticated;
grant select,insert on public.pointage_code_catalogue to authenticated;
grant select,insert,update on public.pointage_code_versions to authenticated;
grant usage on sequence public.pointage_code_versions_id_seq to authenticated;
create policy catalogue_admin_read on public.pointage_code_catalogue for select to authenticated using ((select public.pointage_is_admin()));
create policy catalogue_admin_insert on public.pointage_code_catalogue for insert to authenticated with check ((select public.pointage_is_admin()));
create policy versions_read on public.pointage_code_versions for select to authenticated using (unit_id=(select public.pointage_user_unit()) or (select public.pointage_is_admin()));
create policy versions_insert on public.pointage_code_versions for insert to authenticated with check ((select public.pointage_is_admin()));
create policy versions_update on public.pointage_code_versions for update to authenticated using ((select public.pointage_is_admin())) with check ((select public.pointage_is_admin()));
alter table public.month_codes add column catalogue_id uuid references public.pointage_code_catalogue(id), add column document text;
alter table public.entries add column saved_code text, add column saved_label text, add column saved_document text;
create index pointage_versions_unit_effective on public.pointage_code_versions(unit_id,effective_month,catalogue_id);
-- Keep one catalogue identity for the same existing code across units.
create temporary table seed_identities as select code,gen_random_uuid() id from (select distinct upper(btrim(code)) code from public.month_codes) c;
insert into public.pointage_code_catalogue(id) select id from seed_identities;
update public.month_codes c set catalogue_id=s.id from seed_identities s where upper(btrim(c.code))=s.code;
update public.month_codes set document='ACCORD MOYENS BENEVOLES' where upper(code)='S4';
update public.month_codes set document='ACCORD MOYENS BENEVOLES' where upper(code)='S6';
update public.month_codes set document='ACCORD MOYENS BENEVOLES' where upper(code)='S0';
update public.month_codes set document='AVENANT N°2 ACCORD DROIT SYNDICAL + NOTIFICATION DROIT SYNDICAL EDF + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='D4';
update public.month_codes set document='AVENANT N°2 ACCORD DROIT SYNDICAL + NOTIFICATION DROIT SYNDICAL EDF SA + CRISTALLISATION + DAPE' where upper(code)='L4';
update public.month_codes set document='AVENANT N°2 ACCORD DROIT SYNDICAL + NOTIFICATION DROIT SYNDICAL EDF SA' where upper(code)='E4';
update public.month_codes set document='EN FONCTION DE LA NOTIFICATION FEDERALE OU CONFEDERALE' where upper(code)='N4';
update public.month_codes set document='EN FONCTION DE LA DOTATION DPNT' where upper(code)='81';
update public.month_codes set document='AVENANT N°2 ACCORD CSE + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='1A';
update public.month_codes set document='AVENANT N°2 ACCORD CSE + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='1B';
update public.month_codes set document='AVENANT N°2 ACCORD CSE + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='OA';
update public.month_codes set document='AVENANT N°2 ACCORD CSE + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='1G';
update public.month_codes set document='AVENANT N°2 ACCORD CSE + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='RA';
update public.month_codes set document='AVENANT N°2 ACCORD CSE + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='RB';
update public.month_codes set document='ACCORD CSEC + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='1K';
update public.month_codes set document='ACCORD CSEC + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='1L';
update public.month_codes set document='ACCORD CSEC + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='1R';
update public.month_codes set document='ACCORD CSEC + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='OE';
update public.month_codes set document='ACCORD CSEC + NOTE DECOMPTE DES HEURES DPNT' where upper(code)='OB';
update public.month_codes set document='NOTE DECOMPTE DES HEURES DPNT' where upper(code)='46';
update public.month_codes set document='NOTE DECOMPTE DES HEURES DPNT' where upper(code)='8F';
update public.month_codes set document='NOTE DECOMPTE DES HEURES DPNT' where upper(code)='8G';
update public.month_codes set document='NOTE DECOMPTE DES HEURES DPNT' where upper(code)='Z7';
update public.month_codes set document='AUTANT QUE DE BESOIN' where upper(code)='52';
update public.month_codes set document='CODE DU TRAVAIL' where upper(code)='51';
update public.month_codes set document='COLLECTE CGT POUR INFORMATION / NOTE DECOMPTE DES HEURES DPNT + ACCORDS CSE / DROIT SYNDICAL' where upper(code)='DP';
insert into public.pointage_code_versions(catalogue_id,unit_id,effective_month,code,label,document,active)
 select distinct on (unit_id,catalogue_id) catalogue_id,unit_id,'1900-01',code,label,coalesce(document,''),active
 from public.month_codes order by unit_id,catalogue_id,month_key desc,id desc;
update public.entries e set saved_code=c.code,saved_label=c.label,saved_document=coalesce(c.document,'') from public.month_codes c where c.id=e.code_id;

create function pointage_internal.capture_entry_code() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if TG_OP='INSERT' or new.code_id is distinct from old.code_id then
  select c.code,c.label,coalesce(c.document,'') into new.saved_code,new.saved_label,new.saved_document
   from public.month_codes c where c.id=new.code_id and c.unit_id=new.unit_id and c.month_key=new.month_key;
 else
  new.saved_code:=old.saved_code;new.saved_label:=old.saved_label;new.saved_document:=old.saved_document;
 end if;
 return new;
end;$$;
revoke all on function pointage_internal.capture_entry_code() from public,anon,authenticated;
create trigger entries_capture_code before insert or update on public.entries for each row execute function pointage_internal.capture_entry_code();

-- Synchronise open months only. Recorded entries retain their original names.
create function pointage_internal.sync_codes(p_unit uuid,p_from text) returns void language plpgsql security definer set search_path='' as $$
declare m record; v record;
begin
 if auth.uid() is null or not (public.pointage_is_admin() or p_unit=public.pointage_user_unit()) then raise exception 'Accès refusé' using errcode='42501';end if;
 perform pg_advisory_xact_lock(hashtextextended(p_unit::text,0));
 for m in select month_key from public.months where unit_id=p_unit and month_key>=greatest(p_from,to_char(current_date,'YYYY-MM')) and is_open order by month_key loop
  if exists(select 1 from (select distinct on (catalogue_id) code,active from public.pointage_code_versions where unit_id=p_unit and effective_month<=m.month_key order by catalogue_id,effective_month desc) q group by upper(code) having count(*)>1) then raise exception 'Deux codes identiques pour le mois %',m.month_key;end if;
  for v in select distinct on(catalogue_id) * from public.pointage_code_versions where unit_id=p_unit and effective_month<=m.month_key order by catalogue_id,effective_month desc loop
   update public.month_codes set code=v.code,label=v.label,document=v.document,active=v.active where unit_id=p_unit and month_key=m.month_key and catalogue_id=v.catalogue_id;
   if not found then insert into public.month_codes(unit_id,month_key,catalogue_id,code,label,document,active) values(p_unit,m.month_key,v.catalogue_id,v.code,v.label,v.document,v.active);end if;
  end loop;
 end loop;
end;$$;
revoke all on function pointage_internal.sync_codes(uuid,text) from public,anon;
grant execute on function pointage_internal.sync_codes(uuid,text) to authenticated;

create function pointage_internal.ensure_year(p_unit uuid,p_year integer) returns void language plpgsql security definer set search_path='' as $$
begin
 if auth.uid() is null or not (public.pointage_is_admin() or p_unit=public.pointage_user_unit()) then raise exception 'Accès refusé' using errcode='42501';end if;
 if p_year<1900 or p_year>9999 or p_year is null then raise exception 'Année invalide';end if;
 if not exists(select 1 from public.units where id=p_unit and active and name<>'ADMIN') then return;end if;
 perform pg_advisory_xact_lock(hashtextextended(p_unit::text,0));
 if not exists(select 1 from public.pointage_code_versions where unit_id=p_unit) then
  insert into public.pointage_code_versions(catalogue_id,unit_id,effective_month,code,label,document,active)
  select distinct on(catalogue_id) catalogue_id,p_unit,'1900-01',code,label,document,active from public.pointage_code_versions where effective_month='1900-01' order by catalogue_id,id;
 end if;
 insert into public.months(unit_id,month_key,is_open) select p_unit,p_year::text||'-'||lpad(n::text,2,'0'),true from generate_series(1,12) n on conflict do nothing;
 -- Never update a pre-existing past month when an old year is opened.
 perform pointage_internal.sync_codes(p_unit,greatest(p_year::text||'-01',to_char(current_date,'YYYY-MM')));
 -- Fill empty historical months while preserving existing snapshots.
 insert into public.month_codes(unit_id,month_key,catalogue_id,code,label,document,active)
 select p_unit,m.month_key,v.catalogue_id,v.code,v.label,v.document,v.active from public.months m
 cross join lateral (select distinct on(catalogue_id) * from public.pointage_code_versions where unit_id=p_unit and effective_month<=m.month_key order by catalogue_id,effective_month desc) v
 where m.unit_id=p_unit and m.month_key like p_year::text||'-%'
 and not exists(select 1 from public.month_codes c where c.unit_id=p_unit and c.month_key=m.month_key)
 on conflict do nothing;
end;$$;
revoke all on function pointage_internal.ensure_year(uuid,integer) from public,anon;
grant execute on function pointage_internal.ensure_year(uuid,integer) to authenticated;
create function public.pointage_ensure_year(p_unit_id uuid,p_year integer) returns void language sql security invoker set search_path='' as $$select pointage_internal.ensure_year(p_unit_id,p_year)$$;
revoke all on function public.pointage_ensure_year(uuid,integer) from public,anon;
grant execute on function public.pointage_ensure_year(uuid,integer) to authenticated;

create function public.pointage_save_catalogue(p_units uuid[],p_effective text,p_changes jsonb) returns void language plpgsql security invoker set search_path='' as $$
declare u uuid;c jsonb;key uuid; boundary text;
begin
 if auth.uid() is null or not public.pointage_is_admin() then raise exception 'Action réservée à l’administrateur' using errcode='42501';end if;
 if p_effective !~ '^[1-9][0-9]{3}-(0[1-9]|1[0-2])$' or p_effective<to_char(current_date,'YYYY-MM') or p_effective is null then raise exception 'Choisis le mois en cours ou un mois futur';end if;
 if coalesce(array_length(p_units,1),0)=0 or p_changes is null or jsonb_typeof(p_changes)<>'array' then raise exception 'Unités ou codes manquants';end if;
 foreach u in array p_units loop
  if not exists(select 1 from public.units where id=u and active and name<>'ADMIN') then raise exception 'Unité inconnue ou inactive';end if;
  perform pg_advisory_xact_lock(hashtextextended(u::text,0));
 end loop;
 for c in select value from jsonb_array_elements(p_changes) loop
  key:=nullif(c->>'catalogue_id','')::uuid;
  if key is null then insert into public.pointage_code_catalogue default values returning id into key;end if;
  foreach u in array p_units loop
   insert into public.pointage_code_versions(catalogue_id,unit_id,effective_month,code,label,document,active)
   values(key,u,p_effective,upper(btrim(c->>'code')),btrim(c->>'label'),coalesce(c->>'document',''),coalesce((c->>'active')::boolean,true))
   on conflict(catalogue_id,unit_id,effective_month) do update set code=excluded.code,label=excluded.label,document=excluded.document,active=excluded.active;
  end loop;
 end loop;
 foreach u in array p_units loop
  for boundary in select distinct effective_month from public.pointage_code_versions where unit_id=u and effective_month>=p_effective loop
   if exists(select 1 from (select distinct on(catalogue_id) code from public.pointage_code_versions where unit_id=u and effective_month<=boundary order by catalogue_id,effective_month desc) v group by upper(code) having count(*)>1) then raise exception 'Deux codes identiques à partir de %',boundary;end if;
  end loop;
  perform pointage_internal.sync_codes(u,p_effective);
 end loop;
end;$$;
revoke all on function public.pointage_save_catalogue(uuid[],text,jsonb) from public,anon;
grant execute on function public.pointage_save_catalogue(uuid[],text,jsonb) to authenticated;

CREATE OR REPLACE FUNCTION public.pointage_save_entries(p_unit_id uuid, p_month_key text, p_entries jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
DECLARE own_id uuid:=auth.uid(); month_open boolean;
BEGIN
  IF own_id IS NULL OR p_unit_id IS DISTINCT FROM public.pointage_user_unit() OR public.pointage_is_admin() THEN
    RAISE EXCEPTION 'Seul un utilisateur actif peut enregistrer son pointage dans son unité' USING ERRCODE='42501';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_unit_id::text,0));
  SELECT is_open INTO month_open FROM public.months WHERE unit_id=p_unit_id AND month_key=p_month_key;
  IF month_open IS DISTINCT FROM true THEN RAISE EXCEPTION 'Ce mois est fermé ou indisponible'; END IF;
  IF p_entries IS NULL OR jsonb_typeof(p_entries)<>'array' THEN RAISE EXCEPTION 'Saisies invalides'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_entries) e WHERE e->>'code_id' IS NULL OR e->>'hours' IS NULL OR (e->>'hours')::numeric<0) THEN
    RAISE EXCEPTION 'Chaque saisie doit avoir un code et des heures positives ou nulles';
  END IF;
  IF (SELECT count(*) FROM jsonb_array_elements(p_entries)) <>
     (SELECT count(DISTINCT (e->>'code_id')::bigint) FROM jsonb_array_elements(p_entries) e) THEN
    RAISE EXCEPTION 'Un même code ne peut apparaître qu’une fois dans le mois';
  END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_entries) e WHERE NOT EXISTS(
    SELECT 1 FROM public.month_codes c WHERE c.id=(e->>'code_id')::bigint AND c.unit_id=p_unit_id AND c.month_key=p_month_key
      AND (c.active OR EXISTS(SELECT 1 FROM public.entries old WHERE old.user_id=own_id AND old.unit_id=p_unit_id AND old.month_key=p_month_key AND old.code_id=c.id))
  )) THEN RAISE EXCEPTION 'Un code ne correspond pas au mois ou à l’unité'; END IF;
  DELETE FROM public.entries WHERE user_id=own_id AND unit_id=p_unit_id AND month_key=p_month_key AND code_id NOT IN (SELECT (e->>'code_id')::bigint FROM jsonb_array_elements(p_entries) e);
  INSERT INTO public.entries(user_id,unit_id,month_key,code_id,hours)
    SELECT own_id,p_unit_id,p_month_key,(e->>'code_id')::bigint,round((e->>'hours')::numeric,2) FROM jsonb_array_elements(p_entries) e
    ON CONFLICT(user_id,month_key,code_id) DO UPDATE SET hours=excluded.hours,updated_at=now();
END;
$function$

